Inform users they installed solc through snap (#1124)
TLDR: If you install solc from snap universal Linux packages, it breaks Manticore API as it uses temporary files. Also Manticore won't work when fired on files in `/tmp` (because `solc` doesn't).

Below you can see it in action for a file located in `/tmp`:

```bash
➜ manticore s.sol 
2018-09-07 11:39:03,268: [19239] m.main:INFO: Beginning analysis
2018-09-07 11:39:03,269: [19239] m.ethereum:INFO: Starting symbolic create contract
Traceback (most recent call last):
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1542, in _run_solc
    return json.loads(stdout.decode()), stderr.decode()
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dc/.venv/manticore/bin/manticore", line 11, in <module>
    load_entry_point('manticore', 'console_scripts', 'manticore')()
  File "/home/dc/projects/manticore/manticore/__main__.py", line 191, in main
    ethereum_cli(args)
  File "/home/dc/projects/manticore/manticore/__main__.py", line 173, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], contract_name=args.contract, tx_limit=args.txlimit, tx_use_coverage=not args.txnocoverage, tx_send_ether=not args.txnoether, tx_account=args.txaccount)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 2125, in multi_tx_analysis
    contract_account = self.solidity_create_contract(f, contract_name=contract_name, owner=owner_account, args=args)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1835, in solidity_create_contract
    compile_results = self._compile(source_code, contract_name_i, libraries=deps, solc_bin=solc_bin, solc_remaps=solc_remaps)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1565, in _compile
    output, warnings = ManticoreEVM._run_solc(source_code, solc_bin, solc_remaps)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1544, in _run_solc
    raise EthereumError('Solidity compilation error:\n\n{}'.format(stderr.decode()))
manticore.ethereum.EthereumError: Solidity compilation error:

""s.sol"" is not found
```

And so that's how it looks in action after this commit:
```
➜ manticore s.sol 
2018-09-07 11:38:09,841: [18695] m.main:INFO: Beginning analysis
2018-09-07 11:38:09,842: [18695] m.ethereum:INFO: Starting symbolic create contract
Traceback (most recent call last):
  File "/home/dc/.venv/manticore/bin/manticore", line 11, in <module>
    load_entry_point('manticore', 'console_scripts', 'manticore')()
  File "/home/dc/projects/manticore/manticore/__main__.py", line 191, in main
    ethereum_cli(args)
  File "/home/dc/projects/manticore/manticore/__main__.py", line 173, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], contract_name=args.contract, tx_limit=args.txlimit, tx_use_coverage=not args.txnocoverage, tx_send_ether=not args.txnoether, tx_account=args.txaccount)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 2139, in multi_tx_analysis
    contract_account = self.solidity_create_contract(f, contract_name=contract_name, owner=owner_account, args=args)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1849, in solidity_create_contract
    compile_results = self._compile(source_code, contract_name_i, libraries=deps, solc_bin=solc_bin, solc_remaps=solc_remaps)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1579, in _compile
    output, warnings = ManticoreEVM._run_solc(source_code, solc_bin, solc_remaps)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1552, in _run_solc
    "send us a PR so we could add it here!".format(stderr)
manticore.ethereum.EthereumError: Solidity compilation failed with error: ""s.sol"" is not found

Did you install solc from snap Linux universal packages?
If so, the problem is likely due to snap's sandbox restricting access to /tmp

Here are some potential solutions:
 1) Remove solc from snap and install it different way
 2) Reinstall solc from snap in developer mode, so there is no sandbox
 3) Find a way to add /tmp to the solc's sandbox. If you do, send us a PR so we could add it here!
```