Inform user that solc failed because of snap
Below you can see it in action for this file:

```python
from manticore.ethereum import ManticoreEVM, evm, Operators

m = ManticoreEVM()

source_code = '''
pragma solidity ^0.4.24;

contract Foo {
    function foo() {}
}
'''

user_account = m.create_account(balance=1000, name='user_account')

contract_account = m.solidity_create_contract(source_code, owner=user_account, name='contract_account')
contract_account.foo(1)

print("[+] Now the symbolic values")
symbolic_data = m.make_symbolic_buffer(320)
symbolic_value = m.make_symbolic_value(name="VALUE")
symbolic_address = m.make_symbolic_value(name="ADDRESS")
symbolic_caller = m.make_symbolic_value(name="CALLER")
m.transaction(
    caller=symbolic_caller,
    address=symbolic_address,
    data=symbolic_data,
    value=symbolic_value
)

m.finalize()
print("[+] Look for results in %s " % m.workspace)
```

And so that's how it looks in action:
```
$ python manticore_ex.py
Traceback (most recent call last):
  File "manticore_ex.py", line 15, in <module>
    contract_account = m.solidity_create_contract(source_code, owner=user_account, name='contract_account')
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1851, in solidity_create_contract
    compile_results = self._compile(source_code, contract_name_i, libraries=deps, solc_bin=solc_bin, solc_remaps=solc_remaps)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1579, in _compile
    output, warnings = ManticoreEVM._run_solc(temp, solc_bin, solc_remaps)
  File "/home/dc/projects/manticore/manticore/ethereum.py", line 1554, in _run_solc
    "send us a PR so we could add it here!".format(stderr)
manticore.ethereum.EthereumError: Solidity compilation failed with error: ""tmp7z74dszw"" is not found

Did you install solc from snap Linux universal packages?
If so, the problem occurs because of snap's sandbox which makes so the sandboxed process doesn't see files in /tmp directory.

Here are some solutions to this problem:
1) Remove solc from snap and install it different way
2) Reinstall solc from snap in developer mode, so there is no sandbox (however you do it on your own risk)
3) Find a way to add /tmp to the solc's sandbox. If you do so, send us a PR so we could add it here!
```