Typo in ManticoreEVM#last_return
Encountered the following trace:

```
Traceback (most recent call last):
  …, in <module>
    m.last_return()
  File "…/manticore/ethereum.py", line 906, in last_return
    return state.platform.last_return
AttributeError: 'EVMWorld' object has no attribute 'last_return'
```

It appears this bug was introduced in commit ed29a22f

The same bug was also lurking in `EVMWorld#run`
https://github.com/trailofbits/manticore/pull/886#issuecomment-386626556