Fix multiple symbolic args solidity_create_contract
The `test_create_contract_two_instances` test was crashing before
this PR, due to calling `make_symbolic_buffer` twice with the same
buffer name (`'INITARGS'`) in `make_symbolic_arguments`.

Here's an example of such crash (from a bit different test code/when I
was developing it, but the idea/error is the same):
```
Error
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/dc/manticore_project/tests/eth_general.py", line 432, in test_create_two_instances_of_contract_no_args
    contract2 = self.mevm.solidity_create_contract(source_code, owner=owner, args=None)
  File "/home/dc/manticore_project/manticore/ethereum/manticore.py", line 587, in solidity_create_contract
    args = self.make_symbolic_arguments(constructor_types)
  File "/home/dc/manticore_project/manticore/ethereum/manticore.py", line 542, in make_symbolic_arguments
    return ABI.deserialize(types, self.make_symbolic_buffer(32, name="INITARGS"))
  File "/home/dc/manticore_project/manticore/ethereum/manticore.py", line 113, in make_symbolic_buffer
    return self.constraints.new_array(index_bits=256, name=name, index_max=size, value_bits=8, taint=frozenset(), avoid_collisions=avoid_collisions)
  File "/home/dc/manticore_project/manticore/core/smtlib/constraints.py", line 348, in new_array
    raise ValueError(f'Name {name} already used')
ValueError: Name INITARGS already used
```