Rebased: add test for "arguments_linux_armv7" binary (#1216)
* add test for "arguments_linux_armv7" binary

* Refactor/clean the code

* More tests asserts

* Fix/remove resource warnings in tests

* Binary tests: add --no-color, use proper python path

* Fix test_basic_arm assert

* Fix arm test

* Debug on travis :_:

* more debug

* Travis debug prints

* debug

* Fix merge conflict

* Fix visited assert?

* Fix test binaries

* Remove debugs and change regex assertions

* Use sys.executable instead of /proc/self/exe

to retrieve Python interperter path in tests (see comment).

* Fix timeout solidity test and wrong type published

It turned out that when we executed Manticore with `--timeout`, it ended
up with an exception:

```
2018-12-04 05:13:27,780: [7836] m.c.manticore:INFO: Verbosity set to 1.
2018-12-04 05:13:31,136: [7892] m.c.executor:ERROR: Exception: 'str' object has no attribute 'testcase'
Traceback (most recent call last):
  File "/home/dc/manticore_project/manticore/core/executor.py", line 471, in run
    self._publish('will_terminate_state', current_state, current_state_id, 'Shutdown')# TerminateState('Shutdown'))
  File "/home/dc/manticore_project/manticore/utils/event.py", line 122, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/dc/manticore_project/manticore/utils/event.py", line 130, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/dc/manticore_project/manticore/ethereum/manticore.py", line 1100, in _terminate_state_callback
    e.testcase = False  # Do not generate a testcase file
AttributeError: 'str' object has no attribute 'testcase'
```

Which occured because we published a string instead of exception
instance in `executor.py:471`:

```
self._publish('will_terminate_state', current_state, current_state_id, 'Shutdown')
```

This has been fixed by changing the `'Shutdown'` to
`TerminateState('Shutdown')`.

* Fix amd/arm visited assertions

* Fix binary tests

* Fix binary tests